### ISSUE TITLE
Unable to deploy on 

### ISSUE THREAD

**Issue by kopal2212** [Hygieia/Hygieia#3224]

**Comment by rvema** [comment]
we are lookin for help in this area. If you find success we would greatly appreciate

**Comment by ramachittala** [comment]
Use below env on your deployment files.
API_HOST, API_PORT, DB_HOST, DB_PORT

**Comment by cristian04** [comment]
Hi! Im also working on this. Should we setup a meeting somehow someday?

**Comment by cristian04** [comment]
I've managed to run these services on kubernetes:
- API
- UI
- Audit-API
- Jira Collector
- GitHub Collector

There are some caveats regarding the state for the collectors, but it works! 
I am currently working on the AWS Collector for the Cloud view and some helm charts for alpha.

**Comment by kopal2212** [comment]
Hello @cristian04, sounds cool. I was able to deploy API, UI in Kubernetes but when I was trying to signup in my dashboard I was getting error user already exists, i also increases the auth. expiration time still the same issue, Later I figure out I had some cors issue as well so I solved it anyhow but then when i tried to signup, it took me to the home page with a cross sign-on API connectivity.

**Comment by kopal2212** [comment]
It would be really helpful @cristian04 if u share your deployment, service and ingress yaml files.

**Comment by Ayush-Goyal-coding** [comment]
Hi we have deployed on kubernetes and that are working fine

This would be the file for hygieia-ui deployment

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hygieia-ui
  labels:
    app: hygieia-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hygieia-ui
  template:
    metadata:
      labels:
        name: hygieia-ui
        app: hygieia-ui
    spec:
      hostname: hygieia-ui
      containers:
      - name: hygieia-ui
        image: <image name here>
        imagePullPolicy: IfNotPresent
        env:
        - name: API_HOST
          value: "hygieia-api"
        - name: API_PORT
          value: <port for api>
        resources:
            limits:
              cpu: <max cpu needed >
              memory: <max mem needed>
            requests:
              cpu: <min cpu needed >
              memory: <min mem needed>
        ports:
        - containerPort: <port>
```
