### ISSUE TITLE
Docker-compose sonar collector issue

### ISSUE THREAD

**Issue by summit123** [Hygieia/Hygieia#928]
Hi,
I have the docker sonar collector properties configured on docker-compose.yml. How do I pull only maybe 3/4 projects of interest rather than pulling everything sonar has. Is it possible? Thanks in advance!

My docker-compose.yml:
```yaml
hygieia-sonar-codequality-collector:
  image: hygieia-sonar-codequality-collector:latest
  container_name: hygieia-sonar-codequality
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  environment:
  - SONAR_CRON=0 0/5 * * * *
  - SONAR_URL=http://sonar.company.com/
  - SONAR_API=http://sonar.company.com/api/projects/index/
  - SONAR_USERNAME=SonarUser
  - SONAR_PASSWORD=SonarUser
  - SONAR_PAGE_SIZE=25
```
